-- Supabase Schema Initialization Script
-- Note: Replace existing data or start fresh based on this schema

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create tables
create table if not exists public.users (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  phone text unique not null,
  password text not null,
  email text,
  role text default 'student'::text,
  status text default 'نشط'::text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  students integer default 0,
  status text default 'نشط'::text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image text
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  image text
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint references public.categories(id) on delete cascade
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null,
  class_id bigint references public.classes(id) on delete cascade,
  teacher_id bigint references public.teachers(id) on delete set null,
  image text
);

create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  name text not null,
  course_id bigint references public.courses(id) on delete cascade
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  name text not null,
  chapter_id bigint references public.chapters(id) on delete cascade,
  views integer default 0,
  max_views integer default 5,
  video_url text,
  pdf_url text
);

create table if not exists public.codes (
  id uuid default uuid_generate_v4() primary key,
  code text unique not null,
  class_id bigint references public.classes(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  chapter_id bigint references public.chapters(id) on delete cascade,
  max_uses integer default 1,
  used_count integer default 0,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.unlocked_chapters (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id) on delete cascade,
  chapter_id bigint references public.chapters(id) on delete cascade,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, chapter_id)
);

create table if not exists public.lesson_views (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete cascade,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.view_counts (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete cascade,
  count integer default 0,
  unique(user_id, lesson_id)
);

-- 2. Configure RLS (Row Level Security)
-- Allow public access for local custom auth (permissive policies)
alter table public.users enable row level security;
create policy "Allow public access users" on public.users for all using (true) with check (true);

alter table public.teachers enable row level security;
create policy "Allow public access teachers" on public.teachers for all using (true) with check (true);

alter table public.categories enable row level security;
create policy "Allow public access categories" on public.categories for all using (true) with check (true);

alter table public.classes enable row level security;
create policy "Allow public access classes" on public.classes for all using (true) with check (true);

alter table public.courses enable row level security;
create policy "Allow public access courses" on public.courses for all using (true) with check (true);

alter table public.chapters enable row level security;
create policy "Allow public access chapters" on public.chapters for all using (true) with check (true);

alter table public.lessons enable row level security;
create policy "Allow public access lessons" on public.lessons for all using (true) with check (true);

alter table public.codes enable row level security;
create policy "Allow public access codes" on public.codes for all using (true) with check (true);

alter table public.unlocked_chapters enable row level security;
create policy "Allow public access unlocked_chapters" on public.unlocked_chapters for all using (true) with check (true);

alter table public.lesson_views enable row level security;
create policy "Allow public access lesson_views" on public.lesson_views for all using (true) with check (true);

alter table public.view_counts enable row level security;
create policy "Allow public access view_counts" on public.view_counts for all using (true) with check (true);

-- Insert admin user (optional default)
insert into public.users (name, phone, password, role) values ('مسؤول المنصة', '01000000000', 'admin', 'admin') on conflict (phone) do nothing;
